apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: hpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:    
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp #main container
        image: nginx:latest 
        ports:
        - name: myapp-port
          containerPort: 8080