apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-pod-autoscaler
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 3
  maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       target:
#         kind: Service
#         name: myapp-svc
#       metricName: net.http.request.count
#       targetValue: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
        target:
        type: Utilization
        averageUtilization: 50   